spring.application.name=product-service

spring.profiles.active=default


spring.config.import=optional:configserver:http://localhost:8888

app.jwt.secret=iqPIlntuYW0IYZPddzI11rAQW7MiFDOAoho4RtjTn20=
app.jwt.expiration-ms=86400000

management.endpoints.web.exposure.include=health, metrics, info
